version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8877:80"
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
