services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8877:80"
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    ports:
      - "8876:5000"
    volumes:
      - ./api:/app
    env_file: .env
    environment:
      - TASTYTRADE_USERNAME
      - TASTYTRADE_PASSWORD
      - TASTYTRADE_URL
      - SPOTGAMMA_USERNAME
      - SPOTGAMMA_PASSWORD
