services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8877:80"
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    ports:
      - "8876:5000"
    volumes:
      - ./api:/app
